name: CI/CD com Deploy Railway

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Rodar testes
        run: ./gradlew test

      - name: Build do projeto
        run: ./gradlew build -x test

  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Linkar serviço Railway
        run: railway link --service thriving-stillness

      - name: Deploy no Railway
        run: railway up --token $RAILWAY_TOKEN
