name: CI/CD com Deploy Railway

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'

      - name: Rodar testes
        run: ./gradlew test

      - name: Build do projeto
        run: ./gradlew build -x test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # espera o job anterior terminar com sucesso

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          command: up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
