name: CI/CD com Deploy Railway

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Aumenta o timeout para builds maiores

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'  # Habilita cache de dependências

      - name: Rodar testes
        run: ./gradlew test

      - name: Build do projeto
        run: ./gradlew build -x test  # Evita rodar testes novamente

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Railway Deploy
        uses: railwayapp/railway-action@v1.2.5
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          serviceName: thriving-stillness
